# Codecov configuration for netweave
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%

  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - internal/
      - pkg/
    carryforward: true

ignore:
  - "**/*_test.go"
  - "**/*_mock.go"
  - "**/mocks/**"
  - "cmd/**"
  - "tests/**"
  - "docs/**"
  - "deployments/**"
  - "scripts/**"
  - "tools/**"
