// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/piwi3910/netweave/internal/adapter"
	"github.com/piwi3910/netweave/internal/graphql/scalars"
)

type ApplyPolicyInput struct {
	PolicyID   *string      `json:"policyId,omitempty"`
	Name       string       `json:"name"`
	PolicyType string       `json:"policyType"`
	Scope      scalars.JSON `json:"scope,omitempty"`
	Rules      scalars.JSON `json:"rules,omitempty"`
	Enabled    bool         `json:"enabled"`
	Extensions scalars.JSON `json:"extensions,omitempty"`
}

type BatchError struct {
	ID    string `json:"id"`
	Error string `json:"error"`
}

type BatchResult struct {
	Successful int           `json:"successful"`
	Failed     int           `json:"failed"`
	Errors     []*BatchError `json:"errors,omitempty"`
}

type CreateDescriptorInput struct {
	Name         string       `json:"name"`
	Version      string       `json:"version"`
	Description  *string      `json:"description,omitempty"`
	ArtifactPath string       `json:"artifactPath"`
	Extensions   scalars.JSON `json:"extensions,omitempty"`
}

type CreateNFDeploymentInput struct {
	DescriptorID       string       `json:"descriptorId"`
	Name               string       `json:"name"`
	ParentDeploymentID *string      `json:"parentDeploymentId,omitempty"`
	Extensions         scalars.JSON `json:"extensions,omitempty"`
}

type CreateResourceInput struct {
	ResourceTypeID string       `json:"resourceTypeId"`
	ResourcePoolID *string      `json:"resourcePoolId,omitempty"`
	GlobalAssetID  *string      `json:"globalAssetId,omitempty"`
	Description    *string      `json:"description,omitempty"`
	Extensions     scalars.JSON `json:"extensions,omitempty"`
}

type CreateResourcePoolInput struct {
	Name             string       `json:"name"`
	Description      *string      `json:"description,omitempty"`
	Location         *string      `json:"location,omitempty"`
	OCloudID         string       `json:"oCloudId"`
	GlobalLocationID *string      `json:"globalLocationId,omitempty"`
	Extensions       scalars.JSON `json:"extensions,omitempty"`
}

type CreateServiceModelInput struct {
	Name        string       `json:"name"`
	Version     string       `json:"version"`
	Description *string      `json:"description,omitempty"`
	Category    *string      `json:"category,omitempty"`
	Template    scalars.JSON `json:"template,omitempty"`
	Extensions  scalars.JSON `json:"extensions,omitempty"`
}

type CreateSubscriptionInput struct {
	Callback               string                   `json:"callback"`
	ConsumerSubscriptionID *string                  `json:"consumerSubscriptionId,omitempty"`
	Filter                 *SubscriptionFilterInput `json:"filter,omitempty"`
}

type CreateTenantInput struct {
	Name        string             `json:"name"`
	Description *string            `json:"description,omitempty"`
	Quotas      *TenantQuotasInput `json:"quotas"`
}

type DeploymentCondition struct {
	Type               string       `json:"type"`
	Status             string       `json:"status"`
	Reason             *string      `json:"reason,omitempty"`
	Message            *string      `json:"message,omitempty"`
	LastTransitionTime scalars.Time `json:"lastTransitionTime"`
}

type DescriptorConnection struct {
	Edges    []*DescriptorEdge `json:"edges"`
	PageInfo *PageInfo         `json:"pageInfo"`
}

type DescriptorEdge struct {
	Node   *NFDeploymentDescriptor `json:"node"`
	Cursor string                  `json:"cursor"`
}

type DescriptorFilter struct {
	Name     *string `json:"name,omitempty"`
	Version  *string `json:"version,omitempty"`
	TenantID *string `json:"tenantId,omitempty"`
}

type ExecuteWorkflowInput struct {
	WorkflowName string       `json:"workflowName"`
	PluginName   *string      `json:"pluginName,omitempty"`
	Parameters   scalars.JSON `json:"parameters,omitempty"`
	Timeout      *string      `json:"timeout,omitempty"`
}

type Mutation struct {
}

type NFDeployment struct {
	ID                 string                      `json:"id"`
	TenantID           *string                     `json:"tenantId,omitempty"`
	DescriptorID       string                      `json:"descriptorId"`
	Name               string                      `json:"name"`
	Status             DeploymentStatus            `json:"status"`
	ParentDeploymentID *string                     `json:"parentDeploymentId,omitempty"`
	Extensions         scalars.JSON                `json:"extensions,omitempty"`
	CreatedAt          scalars.Time                `json:"createdAt"`
	UpdatedAt          scalars.Time                `json:"updatedAt"`
	Descriptor         *NFDeploymentDescriptor     `json:"descriptor,omitempty"`
	StatusDetails      *NFDeploymentStatus         `json:"statusDetails"`
	History            []*NFDeploymentHistoryEntry `json:"history"`
}

type NFDeploymentConnection struct {
	Edges    []*NFDeploymentEdge `json:"edges"`
	PageInfo *PageInfo           `json:"pageInfo"`
}

type NFDeploymentDeletedEvent struct {
	ID        string       `json:"id"`
	DeletedAt scalars.Time `json:"deletedAt"`
}

type NFDeploymentDescriptor struct {
	ID           string          `json:"id"`
	TenantID     *string         `json:"tenantId,omitempty"`
	Name         string          `json:"name"`
	Version      string          `json:"version"`
	Description  *string         `json:"description,omitempty"`
	ArtifactPath string          `json:"artifactPath"`
	Extensions   scalars.JSON    `json:"extensions,omitempty"`
	CreatedAt    scalars.Time    `json:"createdAt"`
	Deployments  []*NFDeployment `json:"deployments"`
}

type NFDeploymentEdge struct {
	Node   *NFDeployment `json:"node"`
	Cursor string        `json:"cursor"`
}

type NFDeploymentFilter struct {
	DescriptorID *string           `json:"descriptorId,omitempty"`
	Status       *DeploymentStatus `json:"status,omitempty"`
	TenantID     *string           `json:"tenantId,omitempty"`
}

type NFDeploymentHistoryEntry struct {
	Timestamp scalars.Time `json:"timestamp"`
	Action    string       `json:"action"`
	Status    string       `json:"status"`
	Message   *string      `json:"message,omitempty"`
	User      *string      `json:"user,omitempty"`
}

type NFDeploymentStatus struct {
	DeploymentID  string                 `json:"deploymentId"`
	Status        DeploymentStatus       `json:"status"`
	Message       *string                `json:"message,omitempty"`
	Conditions    []*DeploymentCondition `json:"conditions,omitempty"`
	Replicas      *int                   `json:"replicas,omitempty"`
	ReadyReplicas *int                   `json:"readyReplicas,omitempty"`
	UpdatedAt     scalars.Time           `json:"updatedAt"`
}

type O2Subscription struct {
	ID                     string                  `json:"id"`
	Callback               string                  `json:"callback"`
	ConsumerSubscriptionID *string                 `json:"consumerSubscriptionId,omitempty"`
	Filter                 *SubscriptionFilterData `json:"filter,omitempty"`
	CreatedAt              scalars.Time            `json:"createdAt"`
	UpdatedAt              scalars.Time            `json:"updatedAt"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
	TotalCount      int     `json:"totalCount"`
}

type Pagination struct {
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
}

type Policy struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	PolicyType string       `json:"policyType"`
	Scope      scalars.JSON `json:"scope,omitempty"`
	Rules      scalars.JSON `json:"rules,omitempty"`
	Enabled    bool         `json:"enabled"`
	Extensions scalars.JSON `json:"extensions,omitempty"`
	AppliedAt  scalars.Time `json:"appliedAt"`
}

type PolicyConnection struct {
	Edges    []*PolicyEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type PolicyEdge struct {
	Node   *Policy `json:"node"`
	Cursor string  `json:"cursor"`
}

type PolicyFilter struct {
	PolicyType *string `json:"policyType,omitempty"`
	Enabled    *bool   `json:"enabled,omitempty"`
}

type Query struct {
}

type ResourceConnection struct {
	Edges    []*ResourceEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type ResourceDeletedEvent struct {
	ID        string       `json:"id"`
	DeletedAt scalars.Time `json:"deletedAt"`
}

type ResourceEdge struct {
	Node   *adapter.Resource `json:"node"`
	Cursor string            `json:"cursor"`
}

type ResourceFilter struct {
	ResourcePoolID *string      `json:"resourcePoolId,omitempty"`
	ResourceTypeID *string      `json:"resourceTypeId,omitempty"`
	Location       *string      `json:"location,omitempty"`
	Labels         scalars.JSON `json:"labels,omitempty"`
	TenantID       *string      `json:"tenantId,omitempty"`
}

type ResourcePoolConnection struct {
	Edges    []*ResourcePoolEdge `json:"edges"`
	PageInfo *PageInfo           `json:"pageInfo"`
}

type ResourcePoolDeletedEvent struct {
	ID        string       `json:"id"`
	DeletedAt scalars.Time `json:"deletedAt"`
}

type ResourcePoolEdge struct {
	Node   *adapter.ResourcePool `json:"node"`
	Cursor string                `json:"cursor"`
}

type ResourcePoolFilter struct {
	OCloudID *string      `json:"oCloudId,omitempty"`
	Location *string      `json:"location,omitempty"`
	Labels   scalars.JSON `json:"labels,omitempty"`
	TenantID *string      `json:"tenantId,omitempty"`
}

type ResourceTypeConnection struct {
	Edges    []*ResourceTypeEdge `json:"edges"`
	PageInfo *PageInfo           `json:"pageInfo"`
}

type ResourceTypeEdge struct {
	Node   *adapter.ResourceType `json:"node"`
	Cursor string                `json:"cursor"`
}

type ResourceTypeFilter struct {
	ResourceClass *string `json:"resourceClass,omitempty"`
	ResourceKind  *string `json:"resourceKind,omitempty"`
	Vendor        *string `json:"vendor,omitempty"`
}

type ServiceModel struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Version     string       `json:"version"`
	Description *string      `json:"description,omitempty"`
	Category    *string      `json:"category,omitempty"`
	Template    scalars.JSON `json:"template,omitempty"`
	Extensions  scalars.JSON `json:"extensions,omitempty"`
	CreatedAt   scalars.Time `json:"createdAt"`
}

type ServiceModelConnection struct {
	Edges    []*ServiceModelEdge `json:"edges"`
	PageInfo *PageInfo           `json:"pageInfo"`
}

type ServiceModelEdge struct {
	Node   *ServiceModel `json:"node"`
	Cursor string        `json:"cursor"`
}

type ServiceModelFilter struct {
	Category *string `json:"category,omitempty"`
}

type SubscriptionConnection struct {
	Edges    []*SubscriptionEdge `json:"edges"`
	PageInfo *PageInfo           `json:"pageInfo"`
}

type SubscriptionEdge struct {
	Node   *O2Subscription `json:"node"`
	Cursor string          `json:"cursor"`
}

type SubscriptionFilterData struct {
	ResourcePoolID *string `json:"resourcePoolId,omitempty"`
	ResourceTypeID *string `json:"resourceTypeId,omitempty"`
	ResourceID     *string `json:"resourceId,omitempty"`
}

type SubscriptionFilterInput struct {
	ResourcePoolID *string `json:"resourcePoolId,omitempty"`
	ResourceTypeID *string `json:"resourceTypeId,omitempty"`
	ResourceID     *string `json:"resourceId,omitempty"`
}

type Tenant struct {
	ID            string                  `json:"id"`
	Name          string                  `json:"name"`
	Description   *string                 `json:"description,omitempty"`
	Quotas        *TenantQuotas           `json:"quotas"`
	Usage         *TenantUsage            `json:"usage"`
	CreatedAt     scalars.Time            `json:"createdAt"`
	UpdatedAt     scalars.Time            `json:"updatedAt"`
	ResourcePools *ResourcePoolConnection `json:"resourcePools"`
	Resources     *ResourceConnection     `json:"resources"`
	NfDeployments *NFDeploymentConnection `json:"nfDeployments"`
}

type TenantConnection struct {
	Edges    []*TenantEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type TenantEdge struct {
	Node   *Tenant `json:"node"`
	Cursor string  `json:"cursor"`
}

type TenantQuotas struct {
	MaxResourcePools int `json:"maxResourcePools"`
	MaxResources     int `json:"maxResources"`
	MaxDeployments   int `json:"maxDeployments"`
	MaxWorkflows     int `json:"maxWorkflows"`
}

type TenantQuotasInput struct {
	MaxResourcePools int `json:"maxResourcePools"`
	MaxResources     int `json:"maxResources"`
	MaxDeployments   int `json:"maxDeployments"`
	MaxWorkflows     int `json:"maxWorkflows"`
}

type TenantUsage struct {
	ResourcePools int `json:"resourcePools"`
	Resources     int `json:"resources"`
	Deployments   int `json:"deployments"`
	Workflows     int `json:"workflows"`
}

type UpdateNFDeploymentInput struct {
	Extensions scalars.JSON `json:"extensions,omitempty"`
}

type UpdateResourceInput struct {
	Description   *string      `json:"description,omitempty"`
	GlobalAssetID *string      `json:"globalAssetId,omitempty"`
	Extensions    scalars.JSON `json:"extensions,omitempty"`
}

type UpdateResourcePoolInput struct {
	Name        *string      `json:"name,omitempty"`
	Description *string      `json:"description,omitempty"`
	Extensions  scalars.JSON `json:"extensions,omitempty"`
}

type UpdateSubscriptionInput struct {
	Callback *string                  `json:"callback,omitempty"`
	Filter   *SubscriptionFilterInput `json:"filter,omitempty"`
}

type UpdateTenantInput struct {
	Name        *string            `json:"name,omitempty"`
	Description *string            `json:"description,omitempty"`
	Quotas      *TenantQuotasInput `json:"quotas,omitempty"`
}

type WorkflowExecution struct {
	ID           string         `json:"id"`
	WorkflowName string         `json:"workflowName"`
	PluginName   *string        `json:"pluginName,omitempty"`
	Status       WorkflowStatus `json:"status"`
	Parameters   scalars.JSON   `json:"parameters,omitempty"`
	Result       scalars.JSON   `json:"result,omitempty"`
	Error        *string        `json:"error,omitempty"`
	StartedAt    scalars.Time   `json:"startedAt"`
	CompletedAt  *scalars.Time  `json:"completedAt,omitempty"`
}

type WorkflowExecutionConnection struct {
	Edges    []*WorkflowExecutionEdge `json:"edges"`
	PageInfo *PageInfo                `json:"pageInfo"`
}

type WorkflowExecutionEdge struct {
	Node   *WorkflowExecution `json:"node"`
	Cursor string             `json:"cursor"`
}

type WorkflowFilter struct {
	WorkflowName *string         `json:"workflowName,omitempty"`
	PluginName   *string         `json:"pluginName,omitempty"`
	Status       *WorkflowStatus `json:"status,omitempty"`
}

type DeploymentStatus string

const (
	DeploymentStatusPending      DeploymentStatus = "PENDING"
	DeploymentStatusInstalling   DeploymentStatus = "INSTALLING"
	DeploymentStatusInstalled    DeploymentStatus = "INSTALLED"
	DeploymentStatusUpgrading    DeploymentStatus = "UPGRADING"
	DeploymentStatusRollingBack  DeploymentStatus = "ROLLING_BACK"
	DeploymentStatusUninstalling DeploymentStatus = "UNINSTALLING"
	DeploymentStatusFailed       DeploymentStatus = "FAILED"
	DeploymentStatusUnknown      DeploymentStatus = "UNKNOWN"
)

var AllDeploymentStatus = []DeploymentStatus{
	DeploymentStatusPending,
	DeploymentStatusInstalling,
	DeploymentStatusInstalled,
	DeploymentStatusUpgrading,
	DeploymentStatusRollingBack,
	DeploymentStatusUninstalling,
	DeploymentStatusFailed,
	DeploymentStatusUnknown,
}

func (e DeploymentStatus) IsValid() bool {
	switch e {
	case DeploymentStatusPending, DeploymentStatusInstalling, DeploymentStatusInstalled, DeploymentStatusUpgrading, DeploymentStatusRollingBack, DeploymentStatusUninstalling, DeploymentStatusFailed, DeploymentStatusUnknown:
		return true
	}
	return false
}

func (e DeploymentStatus) String() string {
	return string(e)
}

func (e *DeploymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeploymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeploymentStatus", str)
	}
	return nil
}

func (e DeploymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeploymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeploymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkflowStatus string

const (
	WorkflowStatusPending   WorkflowStatus = "PENDING"
	WorkflowStatusRunning   WorkflowStatus = "RUNNING"
	WorkflowStatusCompleted WorkflowStatus = "COMPLETED"
	WorkflowStatusFailed    WorkflowStatus = "FAILED"
	WorkflowStatusCancelled WorkflowStatus = "CANCELLED"
)

var AllWorkflowStatus = []WorkflowStatus{
	WorkflowStatusPending,
	WorkflowStatusRunning,
	WorkflowStatusCompleted,
	WorkflowStatusFailed,
	WorkflowStatusCancelled,
}

func (e WorkflowStatus) IsValid() bool {
	switch e {
	case WorkflowStatusPending, WorkflowStatusRunning, WorkflowStatusCompleted, WorkflowStatusFailed, WorkflowStatusCancelled:
		return true
	}
	return false
}

func (e WorkflowStatus) String() string {
	return string(e)
}

func (e *WorkflowStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkflowStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkflowStatus", str)
	}
	return nil
}

func (e WorkflowStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkflowStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkflowStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
