// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"
)

const cleanupOldAuditEvents = `-- name: CleanupOldAuditEvents :execrows
DELETE FROM audit_events
WHERE timestamp < NOW() - make_interval(days => $1)
`

func (q *Queries) CleanupOldAuditEvents(ctx context.Context, days int32) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupOldAuditEvents, days)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLatestAuditHash = `-- name: GetLatestAuditHash :one
SELECT entry_hash
FROM audit_events
ORDER BY timestamp DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestAuditHash(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getLatestAuditHash)
	var entry_hash string
	err := row.Scan(&entry_hash)
	return entry_hash, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    id, type, tenant_id, user_id, subject,
    resource_type, resource_id, action, details,
    client_ip, user_agent, timestamp,
    prev_hash, entry_hash
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertAuditEventParams struct {
	ID           string          `json:"id"`
	Type         string          `json:"type"`
	TenantID     string          `json:"tenant_id"`
	UserID       string          `json:"user_id"`
	Subject      string          `json:"subject"`
	ResourceType string          `json:"resource_type"`
	ResourceID   string          `json:"resource_id"`
	Action       string          `json:"action"`
	Details      json.RawMessage `json:"details"`
	ClientIp     string          `json:"client_ip"`
	UserAgent    string          `json:"user_agent"`
	Timestamp    time.Time       `json:"timestamp"`
	PrevHash     string          `json:"prev_hash"`
	EntryHash    string          `json:"entry_hash"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ID,
		arg.Type,
		arg.TenantID,
		arg.UserID,
		arg.Subject,
		arg.ResourceType,
		arg.ResourceID,
		arg.Action,
		arg.Details,
		arg.ClientIp,
		arg.UserAgent,
		arg.Timestamp,
		arg.PrevHash,
		arg.EntryHash,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, type, tenant_id, user_id, subject, resource_type, resource_id, action, details, client_ip, user_agent, timestamp, prev_hash, entry_hash FROM audit_events
WHERE ($3::text = '' OR tenant_id = $3::text)
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type ListAuditEventsParams struct {
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
	TenantFilter string `json:"tenant_filter"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.Limit, arg.Offset, arg.TenantFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TenantID,
			&i.UserID,
			&i.Subject,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Details,
			&i.ClientIp,
			&i.UserAgent,
			&i.Timestamp,
			&i.PrevHash,
			&i.EntryHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByType = `-- name: ListAuditEventsByType :many
SELECT id, type, tenant_id, user_id, subject, resource_type, resource_id, action, details, client_ip, user_agent, timestamp, prev_hash, entry_hash FROM audit_events
WHERE type = $1
ORDER BY timestamp DESC
LIMIT $2
`

type ListAuditEventsByTypeParams struct {
	Type  string `json:"type"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListAuditEventsByType(ctx context.Context, arg ListAuditEventsByTypeParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByType, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TenantID,
			&i.UserID,
			&i.Subject,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Details,
			&i.ClientIp,
			&i.UserAgent,
			&i.Timestamp,
			&i.PrevHash,
			&i.EntryHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByUser = `-- name: ListAuditEventsByUser :many
SELECT id, type, tenant_id, user_id, subject, resource_type, resource_id, action, details, client_ip, user_agent, timestamp, prev_hash, entry_hash FROM audit_events
WHERE user_id = $1
ORDER BY timestamp DESC
LIMIT $2
`

type ListAuditEventsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListAuditEventsByUser(ctx context.Context, arg ListAuditEventsByUserParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TenantID,
			&i.UserID,
			&i.Subject,
			&i.ResourceType,
			&i.ResourceID,
			&i.Action,
			&i.Details,
			&i.ClientIp,
			&i.UserAgent,
			&i.Timestamp,
			&i.PrevHash,
			&i.EntryHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsForVerification = `-- name: ListAuditEventsForVerification :many
SELECT id, prev_hash, entry_hash, timestamp
FROM audit_events
ORDER BY timestamp ASC, id ASC
LIMIT $1 OFFSET $2
`

type ListAuditEventsForVerificationParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditEventsForVerificationRow struct {
	ID        string    `json:"id"`
	PrevHash  string    `json:"prev_hash"`
	EntryHash string    `json:"entry_hash"`
	Timestamp time.Time `json:"timestamp"`
}

func (q *Queries) ListAuditEventsForVerification(ctx context.Context, arg ListAuditEventsForVerificationParams) ([]ListAuditEventsForVerificationRow, error) {
	rows, err := q.db.Query(ctx, listAuditEventsForVerification, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsForVerificationRow{}
	for rows.Next() {
		var i ListAuditEventsForVerificationRow
		if err := rows.Scan(
			&i.ID,
			&i.PrevHash,
			&i.EntryHash,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
