// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backends.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const backendAccessExists = `-- name: BackendAccessExists :one
SELECT EXISTS(
    SELECT 1 FROM backend_access
    WHERE tenant_id = $1 AND backend_id = $2
)
`

type BackendAccessExistsParams struct {
	TenantID  string `json:"tenant_id"`
	BackendID string `json:"backend_id"`
}

func (q *Queries) BackendAccessExists(ctx context.Context, arg BackendAccessExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, backendAccessExists, arg.TenantID, arg.BackendID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const backendExists = `-- name: BackendExists :one
SELECT EXISTS(SELECT 1 FROM backend_instances WHERE id = $1)
`

func (q *Queries) BackendExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, backendExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBackend = `-- name: CreateBackend :exec
INSERT INTO backend_instances (
    id, name, category, adapter_type, description,
    config, credentials, status, status_message,
    last_health_check, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateBackendParams struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Category        string             `json:"category"`
	AdapterType     string             `json:"adapter_type"`
	Description     string             `json:"description"`
	Config          []byte             `json:"config"`
	Credentials     []byte             `json:"credentials"`
	Status          string             `json:"status"`
	StatusMessage   string             `json:"status_message"`
	LastHealthCheck pgtype.Timestamptz `json:"last_health_check"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) CreateBackend(ctx context.Context, arg CreateBackendParams) error {
	_, err := q.db.Exec(ctx, createBackend,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.AdapterType,
		arg.Description,
		arg.Config,
		arg.Credentials,
		arg.Status,
		arg.StatusMessage,
		arg.LastHealthCheck,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createBackendAccess = `-- name: CreateBackendAccess :exec
INSERT INTO backend_access (
    id, tenant_id, backend_id, permissions, constraints,
    granted_at, granted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateBackendAccessParams struct {
	ID          string          `json:"id"`
	TenantID    string          `json:"tenant_id"`
	BackendID   string          `json:"backend_id"`
	Permissions json.RawMessage `json:"permissions"`
	Constraints json.RawMessage `json:"constraints"`
	GrantedAt   time.Time       `json:"granted_at"`
	GrantedBy   string          `json:"granted_by"`
}

func (q *Queries) CreateBackendAccess(ctx context.Context, arg CreateBackendAccessParams) error {
	_, err := q.db.Exec(ctx, createBackendAccess,
		arg.ID,
		arg.TenantID,
		arg.BackendID,
		arg.Permissions,
		arg.Constraints,
		arg.GrantedAt,
		arg.GrantedBy,
	)
	return err
}

const createBackendLink = `-- name: CreateBackendLink :exec
INSERT INTO backend_links (ims_id, dms_id, created_at)
VALUES ($1, $2, $3)
`

type CreateBackendLinkParams struct {
	ImsID     string    `json:"ims_id"`
	DmsID     string    `json:"dms_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateBackendLink(ctx context.Context, arg CreateBackendLinkParams) error {
	_, err := q.db.Exec(ctx, createBackendLink, arg.ImsID, arg.DmsID, arg.CreatedAt)
	return err
}

const deleteBackend = `-- name: DeleteBackend :execrows
DELETE FROM backend_instances WHERE id = $1
`

func (q *Queries) DeleteBackend(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackend, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBackendAccess = `-- name: DeleteBackendAccess :execrows
DELETE FROM backend_access WHERE id = $1
`

func (q *Queries) DeleteBackendAccess(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackendAccess, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBackendLink = `-- name: DeleteBackendLink :execrows
DELETE FROM backend_links WHERE ims_id = $1 AND dms_id = $2
`

type DeleteBackendLinkParams struct {
	ImsID string `json:"ims_id"`
	DmsID string `json:"dms_id"`
}

func (q *Queries) DeleteBackendLink(ctx context.Context, arg DeleteBackendLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackendLink, arg.ImsID, arg.DmsID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBackend = `-- name: GetBackend :one
SELECT id, name, category, adapter_type, description, config, credentials, status, status_message, last_health_check, created_at, updated_at FROM backend_instances WHERE id = $1
`

func (q *Queries) GetBackend(ctx context.Context, id string) (BackendInstance, error) {
	row := q.db.QueryRow(ctx, getBackend, id)
	var i BackendInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.AdapterType,
		&i.Description,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.StatusMessage,
		&i.LastHealthCheck,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackendAccess = `-- name: GetBackendAccess :one
SELECT id, tenant_id, backend_id, permissions, constraints, granted_at, granted_by FROM backend_access WHERE id = $1
`

func (q *Queries) GetBackendAccess(ctx context.Context, id string) (BackendAccess, error) {
	row := q.db.QueryRow(ctx, getBackendAccess, id)
	var i BackendAccess
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BackendID,
		&i.Permissions,
		&i.Constraints,
		&i.GrantedAt,
		&i.GrantedBy,
	)
	return i, err
}

const listBackendAccessByBackend = `-- name: ListBackendAccessByBackend :many
SELECT id, tenant_id, backend_id, permissions, constraints, granted_at, granted_by FROM backend_access
WHERE backend_id = $1
ORDER BY granted_at DESC
`

func (q *Queries) ListBackendAccessByBackend(ctx context.Context, backendID string) ([]BackendAccess, error) {
	rows, err := q.db.Query(ctx, listBackendAccessByBackend, backendID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackendAccess{}
	for rows.Next() {
		var i BackendAccess
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BackendID,
			&i.Permissions,
			&i.Constraints,
			&i.GrantedAt,
			&i.GrantedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackendAccessByTenant = `-- name: ListBackendAccessByTenant :many
SELECT id, tenant_id, backend_id, permissions, constraints, granted_at, granted_by FROM backend_access
WHERE tenant_id = $1
ORDER BY granted_at DESC
`

func (q *Queries) ListBackendAccessByTenant(ctx context.Context, tenantID string) ([]BackendAccess, error) {
	rows, err := q.db.Query(ctx, listBackendAccessByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackendAccess{}
	for rows.Next() {
		var i BackendAccess
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BackendID,
			&i.Permissions,
			&i.Constraints,
			&i.GrantedAt,
			&i.GrantedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackends = `-- name: ListBackends :many
SELECT id, name, category, adapter_type, description, config, credentials, status, status_message, last_health_check, created_at, updated_at FROM backend_instances ORDER BY created_at DESC
`

func (q *Queries) ListBackends(ctx context.Context) ([]BackendInstance, error) {
	rows, err := q.db.Query(ctx, listBackends)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackendInstance{}
	for rows.Next() {
		var i BackendInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.AdapterType,
			&i.Description,
			&i.Config,
			&i.Credentials,
			&i.Status,
			&i.StatusMessage,
			&i.LastHealthCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackendsByCategory = `-- name: ListBackendsByCategory :many
SELECT id, name, category, adapter_type, description, config, credentials, status, status_message, last_health_check, created_at, updated_at FROM backend_instances
WHERE category = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBackendsByCategory(ctx context.Context, category string) ([]BackendInstance, error) {
	rows, err := q.db.Query(ctx, listBackendsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackendInstance{}
	for rows.Next() {
		var i BackendInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.AdapterType,
			&i.Description,
			&i.Config,
			&i.Credentials,
			&i.Status,
			&i.StatusMessage,
			&i.LastHealthCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDMSLinksByIMS = `-- name: ListDMSLinksByIMS :many
SELECT bi.id, bi.name, bi.category, bi.adapter_type, bi.description, bi.config, bi.credentials, bi.status, bi.status_message, bi.last_health_check, bi.created_at, bi.updated_at FROM backend_instances bi
INNER JOIN backend_links bl ON bi.id = bl.dms_id
WHERE bl.ims_id = $1
ORDER BY bi.name
`

func (q *Queries) ListDMSLinksByIMS(ctx context.Context, imsID string) ([]BackendInstance, error) {
	rows, err := q.db.Query(ctx, listDMSLinksByIMS, imsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackendInstance{}
	for rows.Next() {
		var i BackendInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.AdapterType,
			&i.Description,
			&i.Config,
			&i.Credentials,
			&i.Status,
			&i.StatusMessage,
			&i.LastHealthCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIMSLinksByDMS = `-- name: ListIMSLinksByDMS :many
SELECT bi.id, bi.name, bi.category, bi.adapter_type, bi.description, bi.config, bi.credentials, bi.status, bi.status_message, bi.last_health_check, bi.created_at, bi.updated_at FROM backend_instances bi
INNER JOIN backend_links bl ON bi.id = bl.ims_id
WHERE bl.dms_id = $1
ORDER BY bi.name
`

func (q *Queries) ListIMSLinksByDMS(ctx context.Context, dmsID string) ([]BackendInstance, error) {
	rows, err := q.db.Query(ctx, listIMSLinksByDMS, dmsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackendInstance{}
	for rows.Next() {
		var i BackendInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.AdapterType,
			&i.Description,
			&i.Config,
			&i.Credentials,
			&i.Status,
			&i.StatusMessage,
			&i.LastHealthCheck,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBackend = `-- name: UpdateBackend :exec
UPDATE backend_instances SET
    name = $2,
    description = $3,
    config = $4,
    credentials = $5,
    status = $6,
    status_message = $7,
    last_health_check = $8,
    updated_at = $9
WHERE id = $1
`

type UpdateBackendParams struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	Config          []byte             `json:"config"`
	Credentials     []byte             `json:"credentials"`
	Status          string             `json:"status"`
	StatusMessage   string             `json:"status_message"`
	LastHealthCheck pgtype.Timestamptz `json:"last_health_check"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) UpdateBackend(ctx context.Context, arg UpdateBackendParams) error {
	_, err := q.db.Exec(ctx, updateBackend,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Credentials,
		arg.Status,
		arg.StatusMessage,
		arg.LastHealthCheck,
		arg.UpdatedAt,
	)
	return err
}

const updateBackendAccess = `-- name: UpdateBackendAccess :exec
UPDATE backend_access SET
    permissions = $2,
    constraints = $3
WHERE id = $1
`

type UpdateBackendAccessParams struct {
	ID          string          `json:"id"`
	Permissions json.RawMessage `json:"permissions"`
	Constraints json.RawMessage `json:"constraints"`
}

func (q *Queries) UpdateBackendAccess(ctx context.Context, arg UpdateBackendAccessParams) error {
	_, err := q.db.Exec(ctx, updateBackendAccess, arg.ID, arg.Permissions, arg.Constraints)
	return err
}

const updateBackendStatus = `-- name: UpdateBackendStatus :exec
UPDATE backend_instances SET
    status = $2,
    status_message = $3,
    last_health_check = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateBackendStatusParams struct {
	ID              string             `json:"id"`
	Status          string             `json:"status"`
	StatusMessage   string             `json:"status_message"`
	LastHealthCheck pgtype.Timestamptz `json:"last_health_check"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

func (q *Queries) UpdateBackendStatus(ctx context.Context, arg UpdateBackendStatusParams) error {
	_, err := q.db.Exec(ctx, updateBackendStatus,
		arg.ID,
		arg.Status,
		arg.StatusMessage,
		arg.LastHealthCheck,
		arg.UpdatedAt,
	)
	return err
}
