// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificates.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCertificatesByStatus = `-- name: CountCertificatesByStatus :many
SELECT status, COUNT(*) AS count
FROM certificate_metadata
GROUP BY status
`

type CountCertificatesByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountCertificatesByStatus(ctx context.Context) ([]CountCertificatesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countCertificatesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCertificatesByStatusRow{}
	for rows.Next() {
		var i CountCertificatesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCertificateMetadata = `-- name: CreateCertificateMetadata :exec
INSERT INTO certificate_metadata (
    serial_number, user_id, tenant_id, common_name, role_name,
    status, issued_at, expires_at, renewed_from, renewed_to,
    renewal_count, last_error, retry_count, next_retry_at,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type CreateCertificateMetadataParams struct {
	SerialNumber string             `json:"serial_number"`
	UserID       string             `json:"user_id"`
	TenantID     string             `json:"tenant_id"`
	CommonName   string             `json:"common_name"`
	RoleName     string             `json:"role_name"`
	Status       string             `json:"status"`
	IssuedAt     time.Time          `json:"issued_at"`
	ExpiresAt    time.Time          `json:"expires_at"`
	RenewedFrom  string             `json:"renewed_from"`
	RenewedTo    string             `json:"renewed_to"`
	RenewalCount int32              `json:"renewal_count"`
	LastError    string             `json:"last_error"`
	RetryCount   int32              `json:"retry_count"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

func (q *Queries) CreateCertificateMetadata(ctx context.Context, arg CreateCertificateMetadataParams) error {
	_, err := q.db.Exec(ctx, createCertificateMetadata,
		arg.SerialNumber,
		arg.UserID,
		arg.TenantID,
		arg.CommonName,
		arg.RoleName,
		arg.Status,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RenewedFrom,
		arg.RenewedTo,
		arg.RenewalCount,
		arg.LastError,
		arg.RetryCount,
		arg.NextRetryAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCertificateMetadata = `-- name: DeleteCertificateMetadata :execrows
DELETE FROM certificate_metadata WHERE serial_number = $1
`

func (q *Queries) DeleteCertificateMetadata(ctx context.Context, serialNumber string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCertificateMetadata, serialNumber)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCertificateMetadata = `-- name: GetCertificateMetadata :one
SELECT serial_number, user_id, tenant_id, common_name, role_name, status, issued_at, expires_at, revoked_at, renewed_at, renewed_from, renewed_to, renewal_count, last_error, retry_count, next_retry_at, created_at, updated_at FROM certificate_metadata WHERE serial_number = $1
`

func (q *Queries) GetCertificateMetadata(ctx context.Context, serialNumber string) (CertificateMetadatum, error) {
	row := q.db.QueryRow(ctx, getCertificateMetadata, serialNumber)
	var i CertificateMetadatum
	err := row.Scan(
		&i.SerialNumber,
		&i.UserID,
		&i.TenantID,
		&i.CommonName,
		&i.RoleName,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RenewedAt,
		&i.RenewedFrom,
		&i.RenewedTo,
		&i.RenewalCount,
		&i.LastError,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertificatesByStatus = `-- name: ListCertificatesByStatus :many
SELECT serial_number, user_id, tenant_id, common_name, role_name, status, issued_at, expires_at, revoked_at, renewed_at, renewed_from, renewed_to, renewal_count, last_error, retry_count, next_retry_at, created_at, updated_at FROM certificate_metadata
WHERE status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCertificatesByStatus(ctx context.Context, status string) ([]CertificateMetadatum, error) {
	rows, err := q.db.Query(ctx, listCertificatesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateMetadatum{}
	for rows.Next() {
		var i CertificateMetadatum
		if err := rows.Scan(
			&i.SerialNumber,
			&i.UserID,
			&i.TenantID,
			&i.CommonName,
			&i.RoleName,
			&i.Status,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RenewedAt,
			&i.RenewedFrom,
			&i.RenewedTo,
			&i.RenewalCount,
			&i.LastError,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByTenant = `-- name: ListCertificatesByTenant :many
SELECT serial_number, user_id, tenant_id, common_name, role_name, status, issued_at, expires_at, revoked_at, renewed_at, renewed_from, renewed_to, renewal_count, last_error, retry_count, next_retry_at, created_at, updated_at FROM certificate_metadata
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCertificatesByTenant(ctx context.Context, tenantID string) ([]CertificateMetadatum, error) {
	rows, err := q.db.Query(ctx, listCertificatesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateMetadatum{}
	for rows.Next() {
		var i CertificateMetadatum
		if err := rows.Scan(
			&i.SerialNumber,
			&i.UserID,
			&i.TenantID,
			&i.CommonName,
			&i.RoleName,
			&i.Status,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RenewedAt,
			&i.RenewedFrom,
			&i.RenewedTo,
			&i.RenewalCount,
			&i.LastError,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificatesByUser = `-- name: ListCertificatesByUser :many
SELECT serial_number, user_id, tenant_id, common_name, role_name, status, issued_at, expires_at, revoked_at, renewed_at, renewed_from, renewed_to, renewal_count, last_error, retry_count, next_retry_at, created_at, updated_at FROM certificate_metadata
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCertificatesByUser(ctx context.Context, userID string) ([]CertificateMetadatum, error) {
	rows, err := q.db.Query(ctx, listCertificatesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateMetadatum{}
	for rows.Next() {
		var i CertificateMetadatum
		if err := rows.Scan(
			&i.SerialNumber,
			&i.UserID,
			&i.TenantID,
			&i.CommonName,
			&i.RoleName,
			&i.Status,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RenewedAt,
			&i.RenewedFrom,
			&i.RenewedTo,
			&i.RenewalCount,
			&i.LastError,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringCertificates = `-- name: ListExpiringCertificates :many
SELECT serial_number, user_id, tenant_id, common_name, role_name, status, issued_at, expires_at, revoked_at, renewed_at, renewed_from, renewed_to, renewal_count, last_error, retry_count, next_retry_at, created_at, updated_at FROM certificate_metadata
WHERE status = 'active'
  AND expires_at <= $1
ORDER BY expires_at ASC
`

func (q *Queries) ListExpiringCertificates(ctx context.Context, expiresAt time.Time) ([]CertificateMetadatum, error) {
	rows, err := q.db.Query(ctx, listExpiringCertificates, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateMetadatum{}
	for rows.Next() {
		var i CertificateMetadatum
		if err := rows.Scan(
			&i.SerialNumber,
			&i.UserID,
			&i.TenantID,
			&i.CommonName,
			&i.RoleName,
			&i.Status,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RenewedAt,
			&i.RenewedFrom,
			&i.RenewedTo,
			&i.RenewalCount,
			&i.LastError,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenewalFailedCertificates = `-- name: ListRenewalFailedCertificates :many
SELECT serial_number, user_id, tenant_id, common_name, role_name, status, issued_at, expires_at, revoked_at, renewed_at, renewed_from, renewed_to, renewal_count, last_error, retry_count, next_retry_at, created_at, updated_at FROM certificate_metadata
WHERE status = 'renewal_failed'
  AND next_retry_at <= $1
ORDER BY next_retry_at ASC
`

func (q *Queries) ListRenewalFailedCertificates(ctx context.Context, nextRetryAt pgtype.Timestamptz) ([]CertificateMetadatum, error) {
	rows, err := q.db.Query(ctx, listRenewalFailedCertificates, nextRetryAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateMetadatum{}
	for rows.Next() {
		var i CertificateMetadatum
		if err := rows.Scan(
			&i.SerialNumber,
			&i.UserID,
			&i.TenantID,
			&i.CommonName,
			&i.RoleName,
			&i.Status,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RenewedAt,
			&i.RenewedFrom,
			&i.RenewedTo,
			&i.RenewalCount,
			&i.LastError,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertificateRenewalFailed = `-- name: UpdateCertificateRenewalFailed :exec
UPDATE certificate_metadata SET
    status = 'renewal_failed',
    last_error = $2,
    retry_count = retry_count + 1,
    next_retry_at = $3,
    updated_at = NOW()
WHERE serial_number = $1
`

type UpdateCertificateRenewalFailedParams struct {
	SerialNumber string             `json:"serial_number"`
	LastError    string             `json:"last_error"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) UpdateCertificateRenewalFailed(ctx context.Context, arg UpdateCertificateRenewalFailedParams) error {
	_, err := q.db.Exec(ctx, updateCertificateRenewalFailed, arg.SerialNumber, arg.LastError, arg.NextRetryAt)
	return err
}

const updateCertificateRenewed = `-- name: UpdateCertificateRenewed :exec
UPDATE certificate_metadata SET
    status = 'renewed',
    renewed_at = NOW(),
    renewed_to = $2,
    renewal_count = renewal_count + 1,
    updated_at = NOW()
WHERE serial_number = $1
`

type UpdateCertificateRenewedParams struct {
	SerialNumber string `json:"serial_number"`
	RenewedTo    string `json:"renewed_to"`
}

func (q *Queries) UpdateCertificateRenewed(ctx context.Context, arg UpdateCertificateRenewedParams) error {
	_, err := q.db.Exec(ctx, updateCertificateRenewed, arg.SerialNumber, arg.RenewedTo)
	return err
}

const updateCertificateRevoked = `-- name: UpdateCertificateRevoked :exec
UPDATE certificate_metadata SET
    status = 'revoked',
    revoked_at = NOW(),
    updated_at = NOW()
WHERE serial_number = $1
`

func (q *Queries) UpdateCertificateRevoked(ctx context.Context, serialNumber string) error {
	_, err := q.db.Exec(ctx, updateCertificateRevoked, serialNumber)
	return err
}

const updateCertificateStatus = `-- name: UpdateCertificateStatus :exec
UPDATE certificate_metadata SET
    status = $2,
    updated_at = NOW()
WHERE serial_number = $1
`

type UpdateCertificateStatusParams struct {
	SerialNumber string `json:"serial_number"`
	Status       string `json:"status"`
}

func (q *Queries) UpdateCertificateStatus(ctx context.Context, arg UpdateCertificateStatusParams) error {
	_, err := q.db.Exec(ctx, updateCertificateStatus, arg.SerialNumber, arg.Status)
	return err
}
