// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliveries.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDelivery = `-- name: GetDelivery :one
SELECT id, event_id, subscription_id, callback_url, status, attempts, max_attempts, last_attempt_at, next_attempt_at, last_error, http_status_code, response_time, created_at, completed_at FROM notification_deliveries WHERE id = $1
`

func (q *Queries) GetDelivery(ctx context.Context, id string) (NotificationDelivery, error) {
	row := q.db.QueryRow(ctx, getDelivery, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SubscriptionID,
		&i.CallbackUrl,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastAttemptAt,
		&i.NextAttemptAt,
		&i.LastError,
		&i.HttpStatusCode,
		&i.ResponseTime,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listDeliveriesByEvent = `-- name: ListDeliveriesByEvent :many
SELECT id, event_id, subscription_id, callback_url, status, attempts, max_attempts, last_attempt_at, next_attempt_at, last_error, http_status_code, response_time, created_at, completed_at FROM notification_deliveries
WHERE event_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeliveriesByEvent(ctx context.Context, eventID string) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SubscriptionID,
			&i.CallbackUrl,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastAttemptAt,
			&i.NextAttemptAt,
			&i.LastError,
			&i.HttpStatusCode,
			&i.ResponseTime,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesBySubscription = `-- name: ListDeliveriesBySubscription :many
SELECT id, event_id, subscription_id, callback_url, status, attempts, max_attempts, last_attempt_at, next_attempt_at, last_error, http_status_code, response_time, created_at, completed_at FROM notification_deliveries
WHERE subscription_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDeliveriesBySubscription(ctx context.Context, subscriptionID string) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SubscriptionID,
			&i.CallbackUrl,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastAttemptAt,
			&i.NextAttemptAt,
			&i.LastError,
			&i.HttpStatusCode,
			&i.ResponseTime,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedDeliveries = `-- name: ListFailedDeliveries :many
SELECT id, event_id, subscription_id, callback_url, status, attempts, max_attempts, last_attempt_at, next_attempt_at, last_error, http_status_code, response_time, created_at, completed_at FROM notification_deliveries
WHERE status = 'failed'
ORDER BY created_at DESC
`

func (q *Queries) ListFailedDeliveries(ctx context.Context) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listFailedDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SubscriptionID,
			&i.CallbackUrl,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastAttemptAt,
			&i.NextAttemptAt,
			&i.LastError,
			&i.HttpStatusCode,
			&i.ResponseTime,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackDelivery = `-- name: TrackDelivery :exec
INSERT INTO notification_deliveries (
    id, event_id, subscription_id, callback_url,
    status, attempts, max_attempts,
    last_attempt_at, next_attempt_at, last_error,
    http_status_code, response_time,
    created_at, completed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (id) DO UPDATE SET
    status = EXCLUDED.status,
    attempts = EXCLUDED.attempts,
    last_attempt_at = EXCLUDED.last_attempt_at,
    next_attempt_at = EXCLUDED.next_attempt_at,
    last_error = EXCLUDED.last_error,
    http_status_code = EXCLUDED.http_status_code,
    response_time = EXCLUDED.response_time,
    completed_at = EXCLUDED.completed_at
`

type TrackDeliveryParams struct {
	ID             string             `json:"id"`
	EventID        string             `json:"event_id"`
	SubscriptionID string             `json:"subscription_id"`
	CallbackUrl    string             `json:"callback_url"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	LastAttemptAt  pgtype.Timestamptz `json:"last_attempt_at"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LastError      string             `json:"last_error"`
	HttpStatusCode int32              `json:"http_status_code"`
	ResponseTime   int64              `json:"response_time"`
	CreatedAt      time.Time          `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) TrackDelivery(ctx context.Context, arg TrackDeliveryParams) error {
	_, err := q.db.Exec(ctx, trackDelivery,
		arg.ID,
		arg.EventID,
		arg.SubscriptionID,
		arg.CallbackUrl,
		arg.Status,
		arg.Attempts,
		arg.MaxAttempts,
		arg.LastAttemptAt,
		arg.NextAttemptAt,
		arg.LastError,
		arg.HttpStatusCode,
		arg.ResponseTime,
		arg.CreatedAt,
		arg.CompletedAt,
	)
	return err
}
