// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID           string          `json:"id"`
	Type         string          `json:"type"`
	TenantID     string          `json:"tenant_id"`
	UserID       string          `json:"user_id"`
	Subject      string          `json:"subject"`
	ResourceType string          `json:"resource_type"`
	ResourceID   string          `json:"resource_id"`
	Action       string          `json:"action"`
	Details      json.RawMessage `json:"details"`
	ClientIp     string          `json:"client_ip"`
	UserAgent    string          `json:"user_agent"`
	Timestamp    time.Time       `json:"timestamp"`
}

type BackendAccess struct {
	ID          string          `json:"id"`
	TenantID    string          `json:"tenant_id"`
	BackendID   string          `json:"backend_id"`
	Permissions json.RawMessage `json:"permissions"`
	Constraints json.RawMessage `json:"constraints"`
	GrantedAt   time.Time       `json:"granted_at"`
	GrantedBy   string          `json:"granted_by"`
}

type BackendInstance struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Category        string             `json:"category"`
	AdapterType     string             `json:"adapter_type"`
	Description     string             `json:"description"`
	Config          []byte             `json:"config"`
	Credentials     []byte             `json:"credentials"`
	Status          string             `json:"status"`
	StatusMessage   string             `json:"status_message"`
	LastHealthCheck pgtype.Timestamptz `json:"last_health_check"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type BackendLink struct {
	ImsID     string    `json:"ims_id"`
	DmsID     string    `json:"dms_id"`
	CreatedAt time.Time `json:"created_at"`
}

type NotificationDelivery struct {
	ID             string             `json:"id"`
	EventID        string             `json:"event_id"`
	SubscriptionID string             `json:"subscription_id"`
	CallbackUrl    string             `json:"callback_url"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	LastAttemptAt  pgtype.Timestamptz `json:"last_attempt_at"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LastError      string             `json:"last_error"`
	HttpStatusCode int32              `json:"http_status_code"`
	ResponseTime   int64              `json:"response_time"`
	CreatedAt      time.Time          `json:"created_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type Role struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Type        string          `json:"type"`
	Description string          `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	TenantID    string          `json:"tenant_id"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type Subscription struct {
	ID                     string    `json:"id"`
	TenantID               string    `json:"tenant_id"`
	Callback               string    `json:"callback"`
	ConsumerSubscriptionID string    `json:"consumer_subscription_id"`
	FilterResourcePoolID   string    `json:"filter_resource_pool_id"`
	FilterResourceTypeID   string    `json:"filter_resource_type_id"`
	FilterResourceID       string    `json:"filter_resource_id"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

type Tenant struct {
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	Status       string          `json:"status"`
	Quota        json.RawMessage `json:"quota"`
	Usage        json.RawMessage `json:"usage"`
	ContactEmail string          `json:"contact_email"`
	Metadata     json.RawMessage `json:"metadata"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type User struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	Subject       string             `json:"subject"`
	CommonName    string             `json:"common_name"`
	Email         string             `json:"email"`
	OauthSubject  string             `json:"oauth_subject"`
	OauthProvider string             `json:"oauth_provider"`
	RoleID        string             `json:"role_id"`
	IsActive      bool               `json:"is_active"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}
