// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (
    id, name, type, description, permissions, tenant_id,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateRoleParams struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Type        string          `json:"type"`
	Description string          `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	TenantID    string          `json:"tenant_id"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.Permissions,
		arg.TenantID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRole = `-- name: GetRole :one
SELECT id, name, type, description, permissions, tenant_id, created_at, updated_at FROM roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Permissions,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, type, description, permissions, tenant_id, created_at, updated_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.Permissions,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, type, description, permissions, tenant_id, created_at, updated_at FROM roles ORDER BY created_at DESC
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.Permissions,
			&i.TenantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, name, type, description, permissions, tenant_id, created_at, updated_at FROM roles
WHERE tenant_id = '' OR tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRolesByTenant(ctx context.Context, tenantID string) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.Permissions,
			&i.TenantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleExists = `-- name: RoleExists :one
SELECT EXISTS(SELECT 1 FROM roles WHERE id = $1)
`

func (q *Queries) RoleExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, roleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const roleExistsByName = `-- name: RoleExistsByName :one
SELECT EXISTS(SELECT 1 FROM roles WHERE name = $1)
`

func (q *Queries) RoleExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, roleExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles SET
    name = $2,
    type = $3,
    description = $4,
    permissions = $5,
    tenant_id = $6,
    updated_at = $7
WHERE id = $1
`

type UpdateRoleParams struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Type        string          `json:"type"`
	Description string          `json:"description"`
	Permissions json.RawMessage `json:"permissions"`
	TenantID    string          `json:"tenant_id"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.Permissions,
		arg.TenantID,
		arg.UpdatedAt,
	)
	return err
}
