// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package dbsqlc

import (
	"context"
	"time"
)

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (
    id, tenant_id, callback, consumer_subscription_id,
    filter_resource_pool_id, filter_resource_type_id, filter_resource_id,
    created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateSubscriptionParams struct {
	ID                     string    `json:"id"`
	TenantID               string    `json:"tenant_id"`
	Callback               string    `json:"callback"`
	ConsumerSubscriptionID string    `json:"consumer_subscription_id"`
	FilterResourcePoolID   string    `json:"filter_resource_pool_id"`
	FilterResourceTypeID   string    `json:"filter_resource_type_id"`
	FilterResourceID       string    `json:"filter_resource_id"`
	CreatedAt              time.Time `json:"created_at"`
	UpdatedAt              time.Time `json:"updated_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSubscription,
		arg.ID,
		arg.TenantID,
		arg.Callback,
		arg.ConsumerSubscriptionID,
		arg.FilterResourcePoolID,
		arg.FilterResourceTypeID,
		arg.FilterResourceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE FROM subscriptions WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, tenant_id, callback, consumer_subscription_id, filter_resource_pool_id, filter_resource_type_id, filter_resource_id, created_at, updated_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, id string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Callback,
		&i.ConsumerSubscriptionID,
		&i.FilterResourcePoolID,
		&i.FilterResourceTypeID,
		&i.FilterResourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, tenant_id, callback, consumer_subscription_id, filter_resource_pool_id, filter_resource_type_id, filter_resource_id, created_at, updated_at FROM subscriptions ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Callback,
			&i.ConsumerSubscriptionID,
			&i.FilterResourcePoolID,
			&i.FilterResourceTypeID,
			&i.FilterResourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByResourcePool = `-- name: ListSubscriptionsByResourcePool :many
SELECT id, tenant_id, callback, consumer_subscription_id, filter_resource_pool_id, filter_resource_type_id, filter_resource_id, created_at, updated_at FROM subscriptions
WHERE filter_resource_pool_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsByResourcePool(ctx context.Context, filterResourcePoolID string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByResourcePool, filterResourcePoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Callback,
			&i.ConsumerSubscriptionID,
			&i.FilterResourcePoolID,
			&i.FilterResourceTypeID,
			&i.FilterResourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByResourceType = `-- name: ListSubscriptionsByResourceType :many
SELECT id, tenant_id, callback, consumer_subscription_id, filter_resource_pool_id, filter_resource_type_id, filter_resource_id, created_at, updated_at FROM subscriptions
WHERE filter_resource_type_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsByResourceType(ctx context.Context, filterResourceTypeID string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByResourceType, filterResourceTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Callback,
			&i.ConsumerSubscriptionID,
			&i.FilterResourcePoolID,
			&i.FilterResourceTypeID,
			&i.FilterResourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByTenant = `-- name: ListSubscriptionsByTenant :many
SELECT id, tenant_id, callback, consumer_subscription_id, filter_resource_pool_id, filter_resource_type_id, filter_resource_id, created_at, updated_at FROM subscriptions
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsByTenant(ctx context.Context, tenantID string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Callback,
			&i.ConsumerSubscriptionID,
			&i.FilterResourcePoolID,
			&i.FilterResourceTypeID,
			&i.FilterResourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriptionExists = `-- name: SubscriptionExists :one
SELECT EXISTS(SELECT 1 FROM subscriptions WHERE id = $1)
`

func (q *Queries) SubscriptionExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, subscriptionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions SET
    callback = $2,
    consumer_subscription_id = $3,
    filter_resource_pool_id = $4,
    filter_resource_type_id = $5,
    filter_resource_id = $6,
    updated_at = $7
WHERE id = $1
`

type UpdateSubscriptionParams struct {
	ID                     string    `json:"id"`
	Callback               string    `json:"callback"`
	ConsumerSubscriptionID string    `json:"consumer_subscription_id"`
	FilterResourcePoolID   string    `json:"filter_resource_pool_id"`
	FilterResourceTypeID   string    `json:"filter_resource_type_id"`
	FilterResourceID       string    `json:"filter_resource_id"`
	UpdatedAt              time.Time `json:"updated_at"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription,
		arg.ID,
		arg.Callback,
		arg.ConsumerSubscriptionID,
		arg.FilterResourcePoolID,
		arg.FilterResourceTypeID,
		arg.FilterResourceID,
		arg.UpdatedAt,
	)
	return err
}
