// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package dbsqlc

import (
	"context"
	"encoding/json"
	"time"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (
    id, name, description, status, quota, usage,
    contact_email, metadata, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateTenantParams struct {
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	Status       string          `json:"status"`
	Quota        json.RawMessage `json:"quota"`
	Usage        json.RawMessage `json:"usage"`
	ContactEmail string          `json:"contact_email"`
	Metadata     json.RawMessage `json:"metadata"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Quota,
		arg.Usage,
		arg.ContactEmail,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const decrementTenantUsage = `-- name: DecrementTenantUsage :exec
UPDATE tenants SET
    usage = jsonb_set(
        usage,
        ARRAY[$2],
        to_jsonb(GREATEST(COALESCE((usage->>$2)::int, 0) - 1, 0))
    ),
    updated_at = NOW()
WHERE id = $1
`

type DecrementTenantUsageParams struct {
	ID      string      `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) DecrementTenantUsage(ctx context.Context, arg DecrementTenantUsageParams) error {
	_, err := q.db.Exec(ctx, decrementTenantUsage, arg.ID, arg.Column2)
	return err
}

const deleteTenant = `-- name: DeleteTenant :execrows
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTenant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, description, status, quota, usage, contact_email, metadata, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Quota,
		&i.Usage,
		&i.ContactEmail,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementTenantUsage = `-- name: IncrementTenantUsage :exec
UPDATE tenants SET
    usage = jsonb_set(
        usage,
        ARRAY[$2],
        to_jsonb(COALESCE((usage->>$2)::int, 0) + 1)
    ),
    updated_at = NOW()
WHERE id = $1
`

type IncrementTenantUsageParams struct {
	ID      string      `json:"id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) IncrementTenantUsage(ctx context.Context, arg IncrementTenantUsageParams) error {
	_, err := q.db.Exec(ctx, incrementTenantUsage, arg.ID, arg.Column2)
	return err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, description, status, quota, usage, contact_email, metadata, created_at, updated_at FROM tenants ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Quota,
			&i.Usage,
			&i.ContactEmail,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantExists = `-- name: TenantExists :one
SELECT EXISTS(SELECT 1 FROM tenants WHERE id = $1)
`

func (q *Queries) TenantExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, tenantExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE tenants SET
    name = $2,
    description = $3,
    status = $4,
    quota = $5,
    usage = $6,
    contact_email = $7,
    metadata = $8,
    updated_at = $9
WHERE id = $1
`

type UpdateTenantParams struct {
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	Status       string          `json:"status"`
	Quota        json.RawMessage `json:"quota"`
	Usage        json.RawMessage `json:"usage"`
	ContactEmail string          `json:"contact_email"`
	Metadata     json.RawMessage `json:"metadata"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.Exec(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Quota,
		arg.Usage,
		arg.ContactEmail,
		arg.Metadata,
		arg.UpdatedAt,
	)
	return err
}
