// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbsqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, tenant_id, subject, common_name, email,
    oauth_subject, oauth_provider, role_id, is_active,
    last_login_at, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateUserParams struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	Subject       string             `json:"subject"`
	CommonName    string             `json:"common_name"`
	Email         string             `json:"email"`
	OauthSubject  string             `json:"oauth_subject"`
	OauthProvider string             `json:"oauth_provider"`
	RoleID        string             `json:"role_id"`
	IsActive      bool               `json:"is_active"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.Subject,
		arg.CommonName,
		arg.Email,
		arg.OauthSubject,
		arg.OauthProvider,
		arg.RoleID,
		arg.IsActive,
		arg.LastLoginAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, subject, common_name, email, oauth_subject, oauth_provider, role_id, is_active, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.CommonName,
		&i.Email,
		&i.OauthSubject,
		&i.OauthProvider,
		&i.RoleID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, subject, common_name, email, oauth_subject, oauth_provider, role_id, is_active, last_login_at, created_at, updated_at FROM users WHERE email = $1 AND email != ''
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.CommonName,
		&i.Email,
		&i.OauthSubject,
		&i.OauthProvider,
		&i.RoleID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByOAuthSubject = `-- name: GetUserByOAuthSubject :one
SELECT id, tenant_id, subject, common_name, email, oauth_subject, oauth_provider, role_id, is_active, last_login_at, created_at, updated_at FROM users WHERE oauth_subject = $1 AND oauth_subject != ''
`

func (q *Queries) GetUserByOAuthSubject(ctx context.Context, oauthSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOAuthSubject, oauthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.CommonName,
		&i.Email,
		&i.OauthSubject,
		&i.OauthProvider,
		&i.RoleID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySubject = `-- name: GetUserBySubject :one
SELECT id, tenant_id, subject, common_name, email, oauth_subject, oauth_provider, role_id, is_active, last_login_at, created_at, updated_at FROM users WHERE subject = $1 AND subject != ''
`

func (q *Queries) GetUserBySubject(ctx context.Context, subject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySubject, subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Subject,
		&i.CommonName,
		&i.Email,
		&i.OauthSubject,
		&i.OauthProvider,
		&i.RoleID,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, subject, common_name, email, oauth_subject, oauth_provider, role_id, is_active, last_login_at, created_at, updated_at FROM users WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUsersByTenant(ctx context.Context, tenantID string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Subject,
			&i.CommonName,
			&i.Email,
			&i.OauthSubject,
			&i.OauthProvider,
			&i.RoleID,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    tenant_id = $2,
    subject = $3,
    common_name = $4,
    email = $5,
    oauth_subject = $6,
    oauth_provider = $7,
    role_id = $8,
    is_active = $9,
    updated_at = $10
WHERE id = $1
`

type UpdateUserParams struct {
	ID            string    `json:"id"`
	TenantID      string    `json:"tenant_id"`
	Subject       string    `json:"subject"`
	CommonName    string    `json:"common_name"`
	Email         string    `json:"email"`
	OauthSubject  string    `json:"oauth_subject"`
	OauthProvider string    `json:"oauth_provider"`
	RoleID        string    `json:"role_id"`
	IsActive      bool      `json:"is_active"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.TenantID,
		arg.Subject,
		arg.CommonName,
		arg.Email,
		arg.OauthSubject,
		arg.OauthProvider,
		arg.RoleID,
		arg.IsActive,
		arg.UpdatedAt,
	)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)
`

func (q *Queries) UserExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
