apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-init
  namespace: vault-system
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: init
